services:
  - type: web
    name: resume-roaster
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false # Will be set manually in Render dashboard
    autoDeploy: true 